# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='displayName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
