# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_auto_20171225_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParticipationInstances', to='clan.Character'),
        ),
    ]
