# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_auto_20171225_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParticipationInstances', to='clan.Character'),
        ),
    ]
